### PR TITLE
feat(#556): added check circular dependencies

### PR DESCRIPTION
**Pull request by renanbastos93**
Added validation to ensure that dependencies do not form circular dependencies. 
An error is raised if such a condition is detected.

ISSUE: #556 
Repository reference to simulate it: https://github.com/renanbastos93/weaver-issue-556

### CODE REVIEW

**Comment by renanbastos93** [comment]
@mwhittaker @sysulq @rgrandl  

Does anyone have comments on this? Is it good, or do I need to change this commit?

**Comment by rgrandl** [comment]
@renanbastos93, thanks for the PR. 

Few comments:
1) We already have a graph package, so we would prefer not to get a dependency on another graph library (`github.com/dominikbraun/graph`)
2) A better place to check for circular dependencies is in the deployer. For example, in the `multi` deployer, you can do the check when you read the component graph `https://github.com/ServiceWeaver/weaver/blob/main/internal/tool/multi/deployer.go#L250`. Similar path should exist for the other deployers.

**Comment by renanbastos93** [comment]
> @renanbastos93, thanks for the PR.
> 
> Few comments:
> 
> 1. We already have a graph package, so we would prefer not to get a dependency on another graph library (`github.com/dominikbraun/graph`)
> 2. A better place to check for circular dependencies is in the deployer. For example, in the `multi` deployer, you can do the check when you read the component graph `https://github.com/ServiceWeaver/weaver/blob/main/internal/tool/multi/deployer.go#L250`. Similar path should exist for the other deployers.

awesome, i will use that. Thanks a lot soon i will do a new commit.

**Comment by renanbastos93** [comment]
@rgrandl done, check please.

**Review by rgrandl — COMMENTED** [review]
Sorry for the late reply on this, Renan. 

In dfs.go, we have a dfs function that does a DFS traversal of the graph already. Is it possible to modify that function to detect cycles instead of implementing another traversal?

**Comment by renanbastos93** [comment]
> Sorry for the late reply on this, Renan.
> 
> In dfs.go, we have a dfs function that does a DFS traversal of the graph already. Is it possible to modify that function to detect cycles instead of implementing another traversal?

No worries! I can do this, but I will need more time because I've started a new job and my free time has been limited.

**Comment by rgrandl** [comment]
This is not something critical and has been deprioritized.

**Pull request closed without merging**
