### PR TITLE
Fixing escape issues with curl and zsh

### PR DESCRIPTION
**Pull request by danielmapar**
Issue [here](https://github.com/ServiceWeaver/website/issues/2)

### CODE REVIEW

**Comment by mwhittaker** [comment]
Hi @danielmapar! Thanks for the fix. I'm not super familiar with zsh. Could we escape things using single quotes instead of backslashes like this: 

```zsh
curl 'localhost:12345/hello?name=Weaver'
```

If that does work, I think it's a bit easier to read?

**Comment by danielmapar** [comment]
@mwhittaker very good point, and yes `"` works as well. I updated the PR to use `"` instead of escaping chars with `\`.

**Review by mwhittaker — APPROVED** [review]
LGTM!

**Comment by danielmapar** [comment]
I re-based the PR branch @mwhittaker, let me know if I need to do any further steps to get it merged.

**Comment by mwhittaker** [comment]
Merged! Thanks so much for your contribution @danielmapar!

**Pull request merged**
