### PR TITLE
Component interface, struct in different packages.

### PR DESCRIPTION
**Pull request by mwhittaker**
## Overview

Currently, we require that a component interface and its accompanying implementation be in the same package. We've received a number of requests on GitHub (#98, #224) and on our [Discord][discord] to allow the interface and implementation to be in different packages. For example, one user's application generates gRPC server interfaces in one package, and they want to implement these as components in a different package.

Here are four options for how to deal with this issue in increasing order of complexity. This PR implements the second option, but that doesn't mean I think it's the best option. It was quick to implement, and it helped me understand all the options.

## Option 1: Disallow It

This option is trivial. Don't change anything and continue requiring component interfaces and implementations to be in the same package.

## Option 2: Allow It (this PR)

Allow component interfaces and implementations to be in separate packages. This introduces two issues:

1. A developer may forget to link in a component implementation. Before, if you called `weaver.Get[T]`, you were sure to link in the package containing `T`, and therefore you would link in the corresponding implementation of `T`. With this option, `weaver.Get[T]` is not sufficient. A developer must also link in the package with the implementation of `T`.

2. A developer may link multiple implementations of a component. This is the opposite of the previous problem. Previously, we could detect duplicate implementations of the same interface at code generation time, but with this option, that becomes impossible. A user may generate code separately for two packages, each with an implementation of the same interface.

This option appears to have the advantage that it allows people to swap out different implementations of the same interface, which some users have requested. That's true, but it's not so straightforward. If the two components have different configs, for example, swapping is not so easy.

The benefit of this option is that it's simple, and if we encourage people to place their interfaces and implementations in the same package, they shouldn't run into any problems. Only advanced users, who opt to split their interfaces and implementations have the additional burden of remembering to link in one, and only one, implementation.

## Option 3: `weaver.Get[Impl]`

For this option, we change `weaver.Get`. Rather than writing `weaver.Get[Intf]` for some interface `Intf`, developers write `weaver.Get[Impl]` for some implementation type `Impl`. This makes it impossible for a user to forget to link in an implementation, though it still allows them to link multiple implementations.

Implementing this option is a bit tricky because `weaver.Get` still needs to return the interface type, even if it receives the implementation type. I think this is doable though. Here's a rough sketch: https://go.dev/play/p/2L7R6JibaNN. Note that this doesn't build on go 1.20, but it does build on go 1.21.

## Option 4: Impls Are Components

This option builds on Option 3. `weaver.Get` takes an implementation type. However, we take it a step further and make a radical shift in the way we view components. A component is no longer uniquely identified by its interface, but rather by its implementation. Even if two implementations implement the same interface, we view them as distinct components.

This option avoids forgetting to link a component and avoids double linking a component. It's also not so different from the way we had things way back in the day where we automatically generated interfaces from implementations.

[discord]: https://discord.gg/FzbQ3SM8R5

### CODE REVIEW

**Comment by mwhittaker** [comment]
@spetrovic77, @ghemawat, feel free to leave feedback on the four options without digging into the details of this PR. If you want to see an example of this PR in action, it includes a new example app, `greet`, which demonstrates the key changes.

Personally, I prefer Option 1 or 2 because I'm not sure it's worth complicating things to support something that should be rare (interfaces and implementations being in separate packages).

**Review by ghemawat — COMMENTED** [review]
Thanks for the carefully laid out options.

Option #1: the work-around is not hard: Somebody who wants to implement an interface in another package can just make a local type:

```
    type MyType otherpkg.Type
```

Since interfaces have structural typing, instances of MyType can be passed anywhere otherpkg.Type is expected. Would clear documentation in the error message caused by attempting to use a foreign interface fix the issue?

Option 2: makes it too easy to get conflicts at link time (e.g., two packages that work independently just fine, but if put into the same binary, things fail; no way to fix it without getting an author of one of the two packages to make a change, which might break compatibility for users of that package. 

Option 3: metrics, traces, config, etc. would be keyed by the implementation type name? Maybe that's fine. But I am not sure if this is better than #1.

Option 4: What would be the return type here? If we synthesize a component type, we run into old familiar issues:

1. Code generation was touchy; in particular code could not pass around the interface before code generator had run once to create the interface. And that's a chicken and egg problem.
2. We have to synthesize a name for the component type corresponding to the implementation.

**Comment by mwhittaker** [comment]
Let's go with Option 1 then? I can open a new PR to update the error message. @spetrovic77, does this sound good to you as well?

**Comment by spetrovic77** [comment]
> Let's go with Option 1 then? I can open a new PR to update the error message. @spetrovic77, does this sound good to you as well?

Yeah, this makes sense to me, and like Sanjay's said, the interface compatibility makes this an easy issue to fix.

**Pull request closed without merging**
