### PR TITLE
fix crash when failed to open Perfetto database on DashboardCommand()

### PR DESCRIPTION
**Pull request by ymmuse**
This PR fixs crash when failed to open the TraceDB. From the current execution flow of the code, it seems that the failure to open TraceDB will not interrupt the start of the Dashboard service, so the start of the Trace service is placed in the else branch.

### CODE REVIEW

**Review by mwhittaker — APPROVED** [review]
Nice find!

**Comment by mwhittaker** [comment]
Mind rebasing onto main and resolving any conflicts? Then, I'll merge the PR!

**Comment by ymmuse** [comment]
Hi @mwhittaker , I resolved the conflicts.

**Comment by mwhittaker** [comment]
Hey @ymmuse, GitHub is still not letting me merge because of conflicts. I recommend pulling the latest main and then running something like `git rebase --onto main {c4d119b69258932be0365f5551aa63c9a83e164b,~}` to rebase your commit on top of main. Then update the `dashboard` branch and force push.

**Comment by ymmuse** [comment]
Hi @mwhittaker, I make a new PR(#158 ) based on top of main.

**Pull request closed without merging**
