### PR TITLE
Added some tests for proxy.

### PR DESCRIPTION
**Pull request by htiennv**
It seems that the `internal/proxy` package does not have a test file. 
This PR added some test case for check proxy work as expected.

### CODE REVIEW

**Review by rgrandl — COMMENTED** [review]
Can you write a test plan for each test before I take a look?

**Comment by spetrovic77** [comment]
> Can you write a test plan for each test before I take a look?

Just to clarify, I believe @rgrandl was asking for a little comment before each test that describes the setup and what you are testing.

**Comment by tiennv1997** [comment]
Thanks @rgrandl and @spetrovic77. I was added some little comment describes for each test.

**Review by rgrandl — APPROVED** [review]
Nice, sorry for the late late review on this.

**Comment by htiennv** [comment]
Thanks!

**Pull request merged**
